#!/bin/bash

#ddev-generated
## Description: check programatical if the ddev project is running
## Usage: is-running
## Example: usage in shell script: ddev is-running || ddev start

COLOR_RESET="\033[0m"
COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"

if [ "${DDEV_PROJECT_STATUS}" != "running" ]; then
  echo -e "${COLOR_RED}project is ${DDEV_PROJECT} is not running${COLOR_RESET}"
  exit 1;
fi

echo "-e ${COLOR_GREEN}project is ${DDEV_PROJECT} is running${COLOR_RESET}"
